config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'show'    => 'user#show'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div class="container-full">
<%= render 'layouts/header' %>
      <div class="row">
       
        <div class="col-lg-12 text-center v-center">
          
          <h1>Reset password</h1>
          
          <br />
          
          <div class="col-lg-12">
           <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
    
              <%= hidden_field_tag :email, @user.email %>
        
              <%= f.label :password %><br />
              <%= f.password_field :password, class: "input-group input-group-lg col-sm-offset-4 col-sm-4" %><br /><br />
        
              <%= f.label :password_confirmation, "Confirmation" %><br />
              <%= f.password_field :password_confirmation, class: "input-group input-group-lg col-sm-offset-4 col-sm-4" %><br /><br />
        
              <%= f.submit "Update password", class: "btn btn-lg btn-primary" %>
            <% end %>
          </div>
        </div>
        
      </div> <!-- /row -->
  
  	  <div class="row">
       
        <div class="col-lg-12 text-center v-center" style="font-size:39pt;">
          <a href="#"><i class="icon-google-plus"></i></a> <a href="#"><i class="icon-facebook"></i></a>  <a href="#"><i class="icon-twitter"></i></a> <a href="#"><i class="icon-github"></i></a> <a href="#"><i class="icon-pinterest"></i></a>
        </div>
      
      </div>
  
</div> <!-- /container full end -->

app/views/password_resets/new.html.erb
<div class="container-full">
<%= render 'layouts/header' %>
      <div class="row">
       
        <div class="col-lg-12 text-center v-center">
          
          <h1>Forgot password</h1>
          
          <br />
          
          <div class="col-lg-12">
            <%= form_for(:password_reset, url: password_resets_path) do |f| %>
              <%= f.label :email %><br />
              <%= f.email_field :email, class: "input-group input-group-lg col-sm-offset-4 col-sm-4" %><br />
              <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
            <% end %>
          </div>
        </div>
        
      </div> <!-- /row -->
  
  	  <div class="row">
       
        <div class="col-lg-12 text-center v-center" style="font-size:39pt;">
          <a href="#"><i class="icon-google-plus"></i></a> <a href="#"><i class="icon-facebook"></i></a>  <a href="#"><i class="icon-twitter"></i></a> <a href="#"><i class="icon-github"></i></a> <a href="#"><i class="icon-pinterest"></i></a>
        </div>
      
      </div>
  
</div> <!-- /container full end -->